"""update generated_images schema

Revision ID: 383fe2c37168
Revises: a923688ab6c2
Create Date: 2026-07-05 22:59:07.255378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383fe2c37168'
down_revision: Union[str, None] = 'a923688ab6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('generated_images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('generated_images', sa.Column('height', sa.Integer(), nullable=True))
    op.drop_column('generated_images', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('generated_images', 'height')
    op.drop_column('generated_images', 'width')
    op.drop_column('generated_images', 'image_url')
    # ### end Alembic commands ###
