"""Update models

Revision ID: 4a66d1b6c38e
Revises: fe792c6ec011
Create Date: 2026-07-05 21:46:58.534154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a66d1b6c38e'
down_revision: Union[str, None] = 'fe792c6ec011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uploaded_assets_id', table_name='uploaded_assets')
    op.drop_table('uploaded_assets')
    op.alter_column('generated_images', 'filepath', new_column_name='image_path')
    op.add_column('generated_images', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.alter_column('users', 'name', new_column_name='username')
    op.alter_column('users', 'password', new_column_name='hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password', new_column_name='password')
    op.alter_column('users', 'username', new_column_name='name')
    op.drop_column('generated_images', 'model_name')
    op.alter_column('generated_images', 'image_path', new_column_name='filepath')
    op.create_table('uploaded_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stored_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='uploaded_assets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='uploaded_assets_pkey')
    )
    op.create_index('ix_uploaded_assets_id', 'uploaded_assets', ['id'], unique=False)
    # ### end Alembic commands ###
