"""Remove extraneous models

Revision ID: a923688ab6c2
Revises: 4a66d1b6c38e
Create Date: 2026-07-05 21:58:36.865770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a923688ab6c2'
down_revision: Union[str, None] = '4a66d1b6c38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('generated_images_asset_id_fkey', 'generated_images', type_='foreignkey')
    op.drop_column('generated_images', 'asset_id')
    op.drop_index('ix_brand_assets_id', table_name='brand_assets')
    op.drop_table('brand_assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('generated_images_asset_id_fkey', 'generated_images', 'brand_assets', ['asset_id'], ['id'])
    op.create_table('brand_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stored_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='brand_assets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='brand_assets_pkey')
    )
    op.create_index('ix_brand_assets_id', 'brand_assets', ['id'], unique=False)
    # ### end Alembic commands ###
